'use client';
import { useState } from 'react';

// v0 scaffold for: No catalog enrichment via web scraping (images, specs)
// Generated by batch_00 audit. Wire to real API; v0 calls /api/gap-catalog-enrichment-web-scraping-images/run.

export default function CatalogEnrichmentWebScrapingImagesPage() {
  const [input, setInput] = useState('');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch('/api/gap-catalog-enrichment-web-scraping-images/run', {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input }),
      });
      if (!res.ok) {
        throw new Error(`Request failed: ${res.status}`);
      }
      setResult(await res.json());
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '0.5rem' }}>No catalog enrichment via web scraping (images, specs)</h1>
      <p style={{ color: '#666', marginBottom: '1rem' }}>v0 scaffold. Provide input and click Run.</p>
      <textarea
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder="Enter input payload (free text or JSON)..."
        style={{ width: '100%', height: '160px', padding: '12px', border: '1px solid #ddd', borderRadius: '6px', fontFamily: 'monospace' }}
      />
      <div style={{ marginTop: '12px' }}>
        <button
          onClick={run}
          disabled={loading}
          style={{ background: '#0070f3', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px', cursor: loading ? 'wait' : 'pointer' }}
        >
          {loading ? 'Running…' : 'Run'}
        </button>
      </div>
      {error && <pre style={{ marginTop: '16px', color: '#c00', background: '#fee', padding: '12px', borderRadius: '6px' }}>{error}</pre>}
      {result && (
        <pre style={{ marginTop: '16px', background: '#f7f7f7', padding: '12px', borderRadius: '6px', overflow: 'auto', maxHeight: '480px' }}>
          {JSON.stringify(result, null, 2)}
        </pre>
      )}
    </div>
  );
}
