'use client';
import { useState } from 'react';

// v0 scaffold for: Spend-category auto-classification via NLP on invoice line items with GL-code tagging
// Generated by batch_00 audit. Wire to real API; v0 calls /api/cf-spend-category-auto-classification-nlp/run.

export default function SpendCategoryAutoClassificationNlpPage() {
  const [input, setInput] = useState('');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const sampleRequests = [
      {
          "label": "Scenario",
          "value": "Run Spend-category auto-classification via NLP on invoice line items with GL-code tagging for a realistic customer case.\nContext: a team needs a practical recommendation based on incomplete operating data.\nGoal: identify the best action, key risks, missing information, and expected business impact.\nReturn: summary, prioritized action plan, assumptions, and follow-up questions."
      },
      {
          "label": "Data sample",
          "value": "Analyze this Spend-category auto-classification via NLP on invoice line items with GL-code tagging data sample.\nInput records:\n- Record 1: urgent, customer impact high, owner unassigned\n- Record 2: medium priority, blocked by missing data\n- Record 3: recurring issue, automation opportunity\nReturn structured findings, anomalies, recommendations, and confidence."
      },
      {
          "label": "Executive review",
          "value": "Prepare an executive review for Spend-category auto-classification via NLP on invoice line items with GL-code tagging.\nAudience: business owner, operations lead, and implementation team.\nInclude impact, risk, estimated effort, decision points, and a concise next-step plan."
      }
  ];

  const applySampleRequest = (value) => {
    setInput(value);
    setError(null);
    setResult(null);
  };

  async function run() {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch('/api/cf-spend-category-auto-classification-nlp/run', {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input }),
      });
      if (!res.ok) {
        throw new Error(`Request failed: ${res.status}`);
      }
      setResult(await res.json());
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '0.5rem' }}>Spend-category auto-classification via NLP on invoice line items with GL-code tagging</h1>
      <p style={{ color: '#666', marginBottom: '1rem' }}>v0 scaffold. Provide input and click Run.</p>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 10 }}>
          {sampleRequests.map((sample) => (
            <button
              key={sample.label}
              type="button"
              onClick={() => applySampleRequest(sample.value)}
              style={{ padding: '6px 10px', background: '#eef2ff', color: '#1e3a8a', border: '1px solid #c7d2fe', borderRadius: 6, cursor: 'pointer', fontSize: 12, fontWeight: 600 }}
            >
              {sample.label}
            </button>
          ))}
        </div>

      <textarea
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder="Enter input payload (free text or JSON)..."
        style={{ width: '100%', height: '160px', padding: '12px', border: '1px solid #ddd', borderRadius: '6px', fontFamily: 'monospace' }}
      />
      <div style={{ marginTop: '12px' }}>
        <button
          onClick={run}
          disabled={loading}
          style={{ background: '#0070f3', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px', cursor: loading ? 'wait' : 'pointer' }}
        >
          {loading ? 'Running…' : 'Run'}
        </button>
      </div>
      {error && <pre style={{ marginTop: '16px', color: '#c00', background: '#fee', padding: '12px', borderRadius: '6px' }}>{error}</pre>}
      {result && (
        <pre style={{ marginTop: '16px', background: '#f7f7f7', padding: '12px', borderRadius: '6px', overflow: 'auto', maxHeight: '480px' }}>
          {JSON.stringify(result, null, 2)}
        </pre>
      )}
    </div>
  );
}
